---
- name: Windows Server Hardening Scan
  hosts: "{{ target_hosts }}"
  gather_facts: true


  tasks:
  - name: Break Windows
    block:

      - name: Change the guest account name
        community.windows.win_security_policy:
          section: System Access
          key: MaximumPasswordAge
          value: 92
        
    delegate_to: localhost
    run_once: true
