--- 
- 
  gather_facts: true
  hosts: "{{ target_hosts }}"
  name: "Windows Server Hardening Scan"
  tasks: 
    - 
      block: 
        - 
          win_security_policy: 
            key: MaximumPasswordAge
            section: "System Access"
            value: 92
          name: "Change the guest account name"
      delegate_to: localhost
      name: "Break Windows"
      run_once: true
